language: ruby
rvm:
  - 2.2.1
  - 2.1.7
  - 2.0.0
env:
  - DB=sqlite  
  - DB=postgresql
install: gem install -v 1.10.6 bundler --no-rdoc --no-ri  
script:
  - bundle _1.10.6_ install
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - bundle exec rake test
before_script:
  - yes | cp -rf config/database.travis.yml config/database.yml
  - psql -c 'create database nanoblog3_test' -U postgres

branches:
  only:
    - master

notifications:
  hipchat: 372e05a530741a261bec75377fb7c2@nanoblog3

addons:
  code_climate:
    repo_token: af0539bc3f0e9ab93e5e5c71981a42a99cc2d5df28e2bd601e8635b6d348eebf
